version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
  postgres:
    image: postgres:13.3
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  scheduler:
    image: apache/airflow
    command: scheduler
    restart: on-failure
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs

  webserver:
    image: apache/airflow
    entrypoint: ./scripts/entrypoint.sh
    restart: on-failure
    depends_on:
      - postgres
      - scheduler
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8081:8081"

  metabase:
    image: metabase/metabase
    ports:
        - "3000:3000"

  nifi:
    image: apache/nifi:latest
    ports:
        - "9300:9300"

